### ISSUE TITLE
Add iPad Fullscreen Support

### ISSUE THREAD

**Issue by cmazurk** [adrian-ortega/duster-brews-dashboard#9]
Add this tag:

`<meta name="viewport" content="target-densitydpi=device-dpi, width=device-width, user-scalable=no, maximum-scale=1, minimum-scale=1" /> `

**Comment by adrian-ortega** [comment]
This is fixed, updated code here:
https://github.com/adrian-ortega/duster-brews-dashboard/blob/7f75ee6accd344ba6dae12581858515a0d9757f7/views/index.html#L5

**Comment by cmazurk** [comment]
This issue is not yet resolved. In Discord you mentioned that the code I provided was causing an error so you had to revert it. You said you would look into an alternative solution.
